version: '3'
services:
    app: 
        container_name: docker-employee-node-mongo 
        restart: always
        build: .
        ports: 
            - '80:3000'
        links:
            - mongo
    mongo:
        container_name: employee-mongo-db
        image: mongo
        ports: 
            - '27017:27017'
        